name: instagram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  http_client: ^1.5.1
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  flutter_staggered_grid_view: ^0.6.1
  firebase_core: ^1.13.0
  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.20



dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        

